
services:
  angular-ssr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    expose:
      - "4000"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: /nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    depends_on:
      - angular-ssr

networks:
  app-network:
    driver: bridge
